/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tutk_client_FFMPEG_Decoder */

#ifndef _Included_com_tutk_client_FFMPEG_Decoder
#define _Included_com_tutk_client_FFMPEG_Decoder
#ifdef __cplusplus
extern "C" {
#endif
#undef com_tutk_client_FFMPEG_Decoder_MIN_PRIORITY
#define com_tutk_client_FFMPEG_Decoder_MIN_PRIORITY 1L
#undef com_tutk_client_FFMPEG_Decoder_NORM_PRIORITY
#define com_tutk_client_FFMPEG_Decoder_NORM_PRIORITY 5L
#undef com_tutk_client_FFMPEG_Decoder_MAX_PRIORITY
#define com_tutk_client_FFMPEG_Decoder_MAX_PRIORITY 10L
/*
 * Class:     com_tutk_client_FFMPEG_Decoder
 * Method:    init
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tutk_client_FFMPEG_Decoder_init
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_tutk_client_FFMPEG_Decoder
 * Method:    play
 * Signature: ([B[BIIILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_tutk_client_FFMPEG_Decoder_play
        (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jobject);

/*
 * Class:     com_tutk_client_FFMPEG_Decoder
 * Method:    deinit
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tutk_client_FFMPEG_Decoder_deinit
        (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
